server:
  port: 5555

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
      routes:
        - id: backend
          uri: http://localhost:8881
          predicates:
            - Path=/backend/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-backend
logging:
  level:
    org:
      springframework:
        web=TRACE: