server:
  port: 5555

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
      routes:
        - id: backend
          uri: http://localhost:8881
          predicates:
            - Path=/backend/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-backend
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8187
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-auth
        - id: frontend
          uri: http://localhost:8882
          predicates:
            - Path=/app/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market

jwt:
  secret: h4f8093h4f983yhrt98